name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    - cron: "0 3 * * 1"

permissions:
  contents: read
  actions: read
  security-events: write
  
jobs:
  quality:
    if: github.actor != 'dependabot[bot]'
    uses: frasermolyneux/actions/.github/workflows/codequality.yml@main
    with:
      sonar-project-key: frasermolyneux_portal-servers-integration
      sonar-organization: frasermolyneux
      sonar-host-url: https://sonarcloud.io
      build-target: dotnet-web-ci
      dotnet-project: XtremeIdiots.Portal.Integrations.Servers.Api.V1
      dotnet-version: |
        9.0.x
        10.0.x
      src-folder: src
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
